name: test.puppeteer.x11

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            xvfb \
            pulseaudio \
            fonts-noto-color-emoji \
            curl \
            libgbm1 \
            libasound2t64 \
            libnss3 \
            libxss1 \
            libgtk-3-0 \
            libatk-bridge2.0-0 \
            libgdk-pixbuf2.0-0 \
            chromium

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1280x720x24 -ac &
          sleep 3
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Node tools
        run: npm install tiktok-live-connector ws

      - name: Run x11 Stream Server
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          DISPLAY: ":99"
        run: node .github/workflows/server_x11.js
